services:
  app:
    build:
      context: .
      target: development
    ports:
      - "127.0.0.1:8088:8000"
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./public:/app/public
      - ./storage:/app/storage
      - ./tests:/app/tests
      - ./phpunit.xml:/app/phpunit.xml:ro
      - ./phpstan.neon:/app/phpstan.neon:ro
